/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IdodoLpToken extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IdodoLpToken;
  clone(): IdodoLpToken;
  methods: {
    balanceOf(owner: string): NonPayableTransactionObject<string>;

    burn(
      user: string,
      value: number | string
    ): NonPayableTransactionObject<void>;

    mint(
      user: string,
      value: number | string
    ): NonPayableTransactionObject<void>;

    totalSupply(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
